// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSudSksnkjEjhHs0HJjtIQ0BxGEkcR6m4',
    appId: '1:708954029494:web:8c59dc47630dcb05c8d517',
    messagingSenderId: '708954029494',
    projectId: 'mynotes-flutter-project-sk-pua',
    authDomain: 'mynotes-flutter-project-sk-pua.firebaseapp.com',
    storageBucket: 'mynotes-flutter-project-sk-pua.appspot.com',
    measurementId: 'G-82XB9P48WQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkNYxxBipEpwZTWeo9JuTTDYa8V1WaztY',
    appId: '1:708954029494:android:402437ebf08fa283c8d517',
    messagingSenderId: '708954029494',
    projectId: 'mynotes-flutter-project-sk-pua',
    storageBucket: 'mynotes-flutter-project-sk-pua.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLK1x_mhGQcwLPGhdfe6kQ3gleBIHkc9U',
    appId: '1:708954029494:ios:d9df2423354dcc1dc8d517',
    messagingSenderId: '708954029494',
    projectId: 'mynotes-flutter-project-sk-pua',
    storageBucket: 'mynotes-flutter-project-sk-pua.appspot.com',
    iosClientId: '708954029494-tg09dd8s7if2vv2ec79qsjr60o5pvh56.apps.googleusercontent.com',
    iosBundleId: 'se.pixolity.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLK1x_mhGQcwLPGhdfe6kQ3gleBIHkc9U',
    appId: '1:708954029494:ios:d9df2423354dcc1dc8d517',
    messagingSenderId: '708954029494',
    projectId: 'mynotes-flutter-project-sk-pua',
    storageBucket: 'mynotes-flutter-project-sk-pua.appspot.com',
    iosClientId: '708954029494-tg09dd8s7if2vv2ec79qsjr60o5pvh56.apps.googleusercontent.com',
    iosBundleId: 'se.pixolity.mynotes',
  );
}
